[versions]
recyclerview = "1.4.0"
appcompat = "1.7.0"
screenshotty = "1.0.4"
robolectric = "4.14.1"
test-core = "1.6.1"
test-rules = "1.6.1"
test-ext = "1.2.1"
junit = "4.13.2"
truth = "1.4.0"
espresso = "3.6.1"
agp = "8.9.0"
kotlin = "2.0.21"
compose-bom = "2025.03.00"

[libraries]
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
screenshotty = { group = "eu.bolt", name = "screenshotty", version.ref = "screenshotty" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
androidx-test = { group = "androidx.test", name = "core", version.ref = "test-core" }
androidx-test-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
