# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "test-module", "test-module-2" ]
  pull_request:
    branches: [ "master", "test-module", "test-module-2" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.10'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testDebugUnitTest
      - name: Save screenshots
        uses: actions/upload-artifact@v4
        path: "**/*.png"
        retention-days: 2